### ISSUE TITLE
parsing issue with -v 6

### ISSUE THREAD

**Issue by matanbd** [alexandreborges/malwoverview#37]
command:
`python malwoverview.py -v 6 -V 1.1.1.1 -c .malwapi.conf`
output:
```
Traceback (most recent call last):
  File "malwoverview.py", line 11043, in <module>
    vtipwork(ipaddrvtx, urlipvt3)
  File "malwoverview.py", line 803, in vtipwork
    if('as_owner' in vttext['data']['attributes']):
KeyError: 'data'
```
Python 3.8.10

**Comment by alexandreborges** [comment]
Thank you for your message and report. 

I'll check it up, but it seems that ALL VT options are failing and they were working without facing any issue on Sunday, so I need to verify whether is a problem from VT or whether they changed something over the authentication.

Have an excellent day.

**Comment by alexandreborges** [comment]
> command: `python malwoverview.py -v 6 -V 1.1.1.1 -c .malwapi.conf` output:
> 
> ```
> Traceback (most recent call last):
>   File "malwoverview.py", line 11043, in <module>
>     vtipwork(ipaddrvtx, urlipvt3)
>   File "malwoverview.py", line 803, in vtipwork
>     if('as_owner' in vttext['data']['attributes']):
> KeyError: 'data'
> ```
> 
> Python 3.8.10

I've understood what's happening. If you're using REMnux, check if the .malwapi.conf is really in your home directory (/home/remnux) and if it contains the APIs. Probably malwoverview is not being able to find the VT API.

As you can check my image, everything is working fine. 

Have an excellent day.

![image](https://user-images.githubusercontent.com/13165245/201978343-2f632a10-d4a0-469b-9206-8221d205e95f.png)
