### ISSUE TITLE
unable to run : configparser.NoSectionError: No section: 'INQUEST'

### ISSUE THREAD

**Issue by runmalware** [alexandreborges/malwoverview#57]
```
remnux@remnux:~/Downloads/malwaretest1$ ls 
VybMP.dll
remnux@remnux:~/Downloads/malwaretest1$ openssl sha256 VybMP.dll 
SHA256(VybMP.dll)= c0fd1b90093268665e744a6d283fbb250a712020a2bbb138122fbc4fb3185b28

remnux@remnux:~$ malwoverview -d /home/remnux/Downloads/malwaretest1/
Traceback (most recent call last):
  File "/home/remnux/.local/bin/malwoverview", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/remnux/.local/lib/python3.12/site-packages/malwoverview/malwoverview.py", line 117, in main
    INQUESTAPI = config_dict.get('INQUEST', 'INQUESTAPI')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'INQUEST'
remnux@remnux:~$ 

remnux@remnux:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
remnux@remnux:~$ 

remnux@remnux:~$ python3.12
Python 3.12.5 (main, Aug 13 2024, 12:01:39) [GCC 9.4.0] on linux

remnux@remnux:~$ locate malwapi.conf
/home/remnux/.malwapi.conf
/home/remnux/.local/lib/python3.12/site-packages/home/remnux/.malwapi.conf



remnux@remnux:~$ pip3.12 install -U pefile
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pefile in ./.local/lib/python3.12/site-packages (2023.2.7)
remnux@remnux:~$ pip3.12 install -U colorama
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: colorama in ./.local/lib/python3.12/site-packages (0.4.6)
remnux@remnux:~$ pip3.12 install -U simplejson
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: simplejson in ./.local/lib/python3.12/site-packages (3.19.2)
remnux@remnux:~$ pip3.12 install -U python-magic
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-magic in ./.local/lib/python3.12/site-packages (0.4.27)
remnux@remnux:~$ pip3.12 install -U requests
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in ./.local/lib/python3.12/site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.local/lib/python3.12/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./.local/lib/python3.12/site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.local/lib/python3.12/site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.12/site-packages (from requests) (2024.7.4)
remnux@remnux:~$ pip3.12 install -U validators
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: validators in ./.local/lib/python3.12/site-packages (0.33.0)
remnux@remnux:~$ pip3.12 install -U geocoder
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geocoder in ./.local/lib/python3.12/site-packages (1.38.1)
Requirement already satisfied: click in ./.local/lib/python3.12/site-packages (from geocoder) (8.1.7)
Requirement already satisfied: future in ./.local/lib/python3.12/site-packages (from geocoder) (1.0.0)
Requirement already satisfied: ratelim in ./.local/lib/python3.12/site-packages (from geocoder) (0.1.6)
Requirement already satisfied: requests in ./.local/lib/python3.12/site-packages (from geocoder) (2.32.3)
Requirement already satisfied: six in ./.local/lib/python3.12/site-packages (from geocoder) (1.16.0)
Requirement already satisfied: decorator in ./.local/lib/python3.12/site-packages (from ratelim->geocoder) (5.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.local/lib/python3.12/site-packages (from requests->geocoder) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./.local/lib/python3.12/site-packages (from requests->geocoder) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.local/lib/python3.12/site-packages (from requests->geocoder) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.12/site-packages (from requests->geocoder) (2024.7.4)
remnux@remnux:~$ pip3.12 install -U polyswarm-api
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: polyswarm-api in ./.local/lib/python3.12/site-packages (3.9.0)
Requirement already satisfied: requests~=2.31 in ./.local/lib/python3.12/site-packages (from polyswarm-api) (2.32.3)
Requirement already satisfied: python-dateutil~=2.9 in ./.local/lib/python3.12/site-packages (from polyswarm-api) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.12/site-packages (from python-dateutil~=2.9->polyswarm-api) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.local/lib/python3.12/site-packages (from requests~=2.31->polyswarm-api) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./.local/lib/python3.12/site-packages (from requests~=2.31->polyswarm-api) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.local/lib/python3.12/site-packages (from requests~=2.31->polyswarm-api) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.12/site-packages (from requests~=2.31->polyswarm-api) (2024.7.4)
remnux@remnux:~$ pip3.12 install -U pathlib
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pathlib in ./.local/lib/python3.12/site-packages (1.0.1)
remnux@remnux:~$ pip3.12 install -U configparser
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: configparser in ./.local/lib/python3.12/site-packages (7.0.0)
remnux@remnux:~$ 

```

**Comment by alexandreborges** [comment]
Good evening. 

I don't have the same sample, but I suggest you try the command as shown in the image. 
![image](https://github.com/user-attachments/assets/c9e8635f-7c87-4106-848e-3eff2165ce8e)

Have a good Sunday.

**Comment by alexandreborges** [comment]
Dear runmalware, 

Good afternoon. As you haven't commented anything since I replied to you, I will close the issue.

Have a good weekend.
